name: com.geekaid.ifscode
description: "IFSC CODE SEARCH"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4


  core_utility:
    path: /Users/user/Documents/hp/GITHUB/geek_app_lab_packages/core_utility

#  core_calculator:
#    path: /Users/user/Documents/hp/GITHUB/geek_app_lab_packages/core_calculator

  branch_locator:
    path: /Users/user/Documents/hp/GITHUB/geek_app_lab_packages/branch_locator

  cupertino_icons: ^1.0.6

dev_dependencies:
  package_rename: ^1.7.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
