name: emi_calculator
description: "emi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4


  core_utility:
#    path: /home/hitesh-patel/Dev/github/geek_app_lab_packages/core_utility
    path: /Users/user/hp/github/geek_app_lab_packages/core_utility


  # branch_locator:
  #   path: /home/hitesh-patel/Dev/github/geek_app_lab_packages/branch_locator

  core_calculator:
#    path: /home/hitesh-patel/Dev/github/geek_app_lab_packages/core_calculator
    path: /Users/user/hp/github/geek_app_lab_packages/core_calculator


  cupertino_icons: ^1.0.6

dev_dependencies:
  package_rename: ^1.7.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
